name: Update Public Market Data

on:
  schedule:
    - cron: "0 0 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          mkdir -p dist

      # run sync scrpit inplace after procotol open source
      - uses: addnab/docker-run-action@v3
        env:
          HV_URL: ${{ secrets.HV_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.ap-southeast-1.aliyuncs.com
          image: registry.ap-southeast-1.aliyuncs.com/ntnl-y/app-public-data-sync:sha-4f6275594d59686f623464ee3acecd43eb94502e
          options: -e HV_URL -e SUPABASE_URL -e SUPABASE_KEY -v ${{ github.workspace }}/dist:/data/output --user 0:0
          run: |
            node ./lib/index.js

      - run: |
          sudo rm -rf OHLC index
          sudo mv ./dist/OHLC ./dist/index .
          sudo rm -rf dist

      - name: Deploy UI Web on gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: .
          # ISSUE: we need to keep .github to make CI work continuously
          exclude_assets: ""
